"""
make_catalyst_zips.py — VigilanteVanguard Catalyst Deployment Zips
===================================================================
Produces exactly what Catalyst needs:

  vv-backend-catalyst.zip
    └── backend source code for AppSail (Docker)
        Excludes: venv/, __pycache__, .pyc, .env, *.pt (yolov8 model),
                  training_data/*.pkl (trained model files),
                  test_*.py, _diag.py, *.zip
        Includes: training_data/ folder structure (empty dirs only — images
                  are uploaded via the UI after deploy)

  vv-frontend-catalyst.zip
    └── compiled React SPA for Catalyst Slate upload
        Contents of frontend/dist/ only — ready to serve as static files

Run from the project root:
    python make_catalyst_zips.py

After running:
  1. Upload vv-backend-catalyst.zip  → Catalyst Console → AppSail → vv-backend
  2. Upload vv-frontend-catalyst.zip → Catalyst Console → Slate → vv-frontend
"""
import os
import sys
import zipfile

ROOT     = os.path.dirname(os.path.abspath(__file__))
BE_DIR   = os.path.join(ROOT, "backend")
DIST_DIR = os.path.join(ROOT, "frontend", "dist")

OUT_BACKEND  = os.path.join(ROOT, "vv-backend-catalyst.zip")
OUT_FRONTEND = os.path.join(ROOT, "vv-frontend-catalyst.zip")

# ─── Skip rules ───────────────────────────────────────────────────────────────
SKIP_DIRS_BACKEND = {
    "venv", "_venv_bak", "node_modules", "__pycache__",
    ".git", ".idea", ".vscode", ".pytest_cache", ".mypy_cache",
}

SKIP_EXT = {".pyc", ".pyo", ".DS_Store", ".pyd"}

def skip_backend_file(full_path: str, rel_path: str) -> bool:
    """Return True if this file should be excluded from the backend zip."""
    fname = os.path.basename(full_path)
    rel   = rel_path.replace("\\", "/")

    # Never include secrets
    if fname in (".env",):
        return True

    # Large binary model files — re-downloaded by Dockerfile at runtime; not needed in zip
    if fname in ("yolov8n.pt", "yolov11n.pt", "oldyolo.pt") or fname.endswith(".pt"):
        return True

    # Trained ML model pickles — rebuilt after upload via UI
    if fname.endswith(".pkl") and "training_data" in rel:
        return True

    # Benchmark cache — regenerated by benchmark run
    if fname == "_benchmark_results.json" and "training_data" in rel:
        return True

    # Skip test / utility scripts not needed in production
    if fname.startswith("test_") and fname.endswith(".py"):
        return True
    if fname in (
        "_diag.py", "check_thresholds.py", "run_benchmark.py",
        "run_training_pipeline.py", "generate_training_data.py",
        "make_zips.py", "make_focused_zips.py", "make_deploy_zip.py",
        "make_catalyst_zips.py", "deploy_backend.py", "write_launch.py",
        "create-shortcut.vbs", "launch.bat",
    ):
        return True

    # Skip existing zip files inside backend (shouldn't be there but just in case)
    if fname.endswith(".zip"):
        return True

    # Skip extension checks
    if any(fname.endswith(e) for e in SKIP_EXT):
        return True

    return False


def skip_frontend_file(fname: str) -> bool:
    return any(fname.endswith(e) for e in SKIP_EXT)


def count_files(zf: zipfile.ZipFile) -> int:
    return len(zf.namelist())


# ─────────────────────────────────────────────────────────────────────────────
#  1. Backend zip
# ─────────────────────────────────────────────────────────────────────────────
print("=" * 62)
print("  vv-backend-catalyst.zip  (AppSail Docker source)")
print("=" * 62)

if not os.path.isdir(BE_DIR):
    print(f"ERROR: backend/ not found at {BE_DIR}")
    sys.exit(1)

n_be = 0
with zipfile.ZipFile(OUT_BACKEND, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
    for dirpath, dirs, files in os.walk(BE_DIR):
        # Prune skip-dirs in place (prevents os.walk from descending)
        dirs[:] = [
            d for d in dirs
            if d not in SKIP_DIRS_BACKEND and not d.startswith(".")
        ]

        for fname in sorted(files):
            full  = os.path.join(dirpath, fname)
            rel   = os.path.relpath(full, BE_DIR)  # relative to backend/
            if skip_backend_file(full, rel):
                continue
            zf.write(full, rel)
            print(f"  + {rel}")
            n_be += 1

sz_be = os.path.getsize(OUT_BACKEND) / 1_048_576
print(f"\n  {n_be} files  |  {sz_be:.1f} MB")
print(f"  → {OUT_BACKEND}\n")


# ─────────────────────────────────────────────────────────────────────────────
#  2. Frontend zip (dist/ only)
# ─────────────────────────────────────────────────────────────────────────────
print("=" * 62)
print("  vv-frontend-catalyst.zip  (Slate static files)")
print("=" * 62)

if not os.path.isdir(DIST_DIR):
    print(f"\nERROR: frontend/dist/ not found at {DIST_DIR}")
    print("Run first:  cd frontend && npm run build\n")
    sys.exit(1)

n_fe = 0
with zipfile.ZipFile(OUT_FRONTEND, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
    for dirpath, dirs, files in os.walk(DIST_DIR):
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        for fname in sorted(files):
            if skip_frontend_file(fname):
                continue
            full = os.path.join(dirpath, fname)
            rel  = os.path.relpath(full, DIST_DIR)  # relative to dist/
            zf.write(full, rel)
            print(f"  + {rel}")
            n_fe += 1

sz_fe = os.path.getsize(OUT_FRONTEND) / 1_048_576
print(f"\n  {n_fe} files  |  {sz_fe:.1f} MB")
print(f"  >> {OUT_FRONTEND}\n")


# ─────────────────────────────────────────────────────────────────────────────
#  Summary
# ─────────────────────────────────────────────────────────────────────────────
print("=" * 62)
print("  DONE -- 2 deployment zips ready")
print("=" * 62)
print(f"""
  vv-backend-catalyst.zip   {sz_be:.1f} MB
    >> Catalyst Console >> AppSail >> vv-backend >> Upload Source
    >> OR: catalyst deploy (CLI)

  vv-frontend-catalyst.zip  {sz_fe:.1f} MB
    >> Catalyst Console >> Slate >> vv-frontend >> Upload Files
    >> OR: catalyst deploy --client vv-frontend (CLI)

  Checklist before uploading:
  --------------------------
  [ ] Set VV_TOKEN_SECRET env var in AppSail
  [ ] Set GEMINI_API_KEY, GOOGLE_MAPS_API_KEY in AppSail
  [ ] Set ALLOWED_ORIGINS_STR to your AppSail domain
  [ ] Create Stratus bucket: vv-training-data
  [ ] See CATALYST_DEPLOY.md for full checklist
""")
