import os
p = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'launch.bat')
lines = [
    '@echo off\r\n',
    'title VigilanteVanguard - KSP Datathon 2026\r\n',
    'color 1F\r\n',
    'cls\r\n',
    'echo.\r\n',
    'echo  ============================================================\r\n',
    'echo    VigilanteVanguard 4.1 - Karnataka State Police Datathon\r\n',
    'echo    Zoho Catalyst + Qwen2.5 via Ollama (local AI)\r\n',
    'echo  ============================================================\r\n',
    'echo.\r\n',
    'set ROOT=%~dp0\r\n',
    'set BACKEND=%ROOT%backend\r\n',
    'set FRONTEND=%ROOT%frontend\r\n',
    'set VENV_PY=%ROOT%backend\\venv\\Scripts\\python.exe\r\n',
    'python --version >nul 2>&1\r\n',
    'if errorlevel 1 ( echo [ERROR] Python not found & pause & exit /b 1 )\r\n',
    'node --version >nul 2>&1\r\n',
    'if errorlevel 1 ( echo [ERROR] Node not found & pause & exit /b 1 )\r\n',
    'echo  Clearing port 8000...\r\n',
    'for /f "tokens=5" %%P in (\'netstat -ano 2^>nul ^| findstr ":8000 "\') do taskkill /PID %%P /F >nul 2>&1\r\n',
    'echo  Clearing port 3000...\r\n',
    'for /f "tokens=5" %%P in (\'netstat -ano 2^>nul ^| findstr ":3000 "\') do taskkill /PID %%P /F >nul 2>&1\r\n',
    'timeout /t 1 /nobreak >nul\r\n',
    'if not exist "%VENV_PY%" (\r\n',
    '    echo  [1/5] Creating Python venv...\r\n',
    '    python -m venv "%ROOT%backend\\venv"\r\n',
    ') else (\r\n',
    '    echo  [1/5] Venv ready.\r\n',
    ')\r\n',
    'echo  [2/5] Checking backend packages...\r\n',
    '"%VENV_PY%" -c "import fastapi,uvicorn,pydantic" >nul 2>&1\r\n',
    'if errorlevel 1 (\r\n',
    '    echo  Installing backend packages - please wait ~2 mins...\r\n',
    '    "%VENV_PY%" -m pip install -r "%BACKEND%\\requirements.txt" --disable-pip-version-check\r\n',
    ')\r\n',
    'echo  [2/5] Backend packages ready.\r\n',
    'if not exist "%FRONTEND%\\node_modules" (\r\n',
    '    echo  [3/5] Installing frontend packages - please wait...\r\n',
    '    cd /d "%FRONTEND%"\r\n',
    '    npm install\r\n',
    '    cd /d "%ROOT%"\r\n',
    ') else (\r\n',
    '    echo  [3/5] Frontend packages ready.\r\n',
    ')\r\n',
    'echo  [4/5] Starting Ollama (Qwen2.5:1.5b)...\r\n',
    'start "" /b ollama serve\r\n',
    'timeout /t 3 /nobreak >nul\r\n',
    'start "" /b ollama run qwen2.5:1.5b --keepalive 60m\r\n',
    'timeout /t 2 /nobreak >nul\r\n',
    'echo  [4/5] Ollama ready.\r\n',
    'echo  [5/5] Starting backend and frontend...\r\n',
    'start "VV-Backend" cmd /k "cd /d "%BACKEND%" & "%VENV_PY%" -m uvicorn main:app --reload --host 127.0.0.1 --port 8000"\r\n',
    'timeout /t 3 /nobreak >nul\r\n',
    'start "VV-Frontend" cmd /k "cd /d "%FRONTEND%" & npm run dev"\r\n',
    'echo  Waiting for frontend on port 3000...\r\n',
    ':WAIT\r\n',
    'timeout /t 2 /nobreak >nul\r\n',
    'netstat -ano 2>nul | findstr ":3000 " >nul 2>&1\r\n',
    'if errorlevel 1 goto WAIT\r\n',
    'timeout /t 2 /nobreak >nul\r\n',
    'start "" "http://localhost:3000"\r\n',
    'echo.\r\n',
    'echo  ============================================================\r\n',
    'echo   LOCAL DEV RUNNING\r\n',
    'echo   Frontend    -  http://localhost:3000\r\n',
    'echo   API Docs    -  http://localhost:8000/api/docs\r\n',
    'echo   AI Model    -  qwen2.5:1.5b via Ollama (local, no key needed)\r\n',
    'echo.\r\n',
    'echo   LIVE ON CATALYST (any browser, any device):\r\n',
    'echo   https://vv-frontend-pjrowkzp.onslate.in\r\n',
    'echo.\r\n',
    'echo   Login       -  admin@ksp.gov.in / admin123\r\n',
    'echo   To STOP     -  Close VV-Backend and VV-Frontend windows\r\n',
    'echo  ============================================================\r\n',
    'echo.\r\n',
    'pause\r\n',
]
with open(p, 'w', encoding='ascii', newline='') as f:
    f.writelines(lines)
print('launch.bat written OK')
