"""
Smart Reports API — VigilanteVanguard
Generates investigation reports, daily briefings, and PDF exports
via Catalyst SmartBrowz + Catalyst Mail.
"""
from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime, date

from app.core.catalyst import CatalystSmartBrowz, CatalystMail, CatalystStratus, CatalystDataStore
from app.core.auth import AuthUser, require_analyst, require_supervisor
from app.core.config import settings

router = APIRouter()


class ReportRequest(BaseModel):
    report_type: str            # "daily_brief" | "case_summary" | "district_report"
    case_id: Optional[int] = None
    district_id: Optional[int] = None
    period_from: Optional[date] = None
    period_to: Optional[date] = None
    email_recipients: Optional[List[str]] = []


@router.post("/generate", summary="Generate intelligence report PDF")
async def generate_report(
    request: ReportRequest,
    background_tasks: BackgroundTasks,
    current_user: AuthUser = Depends(require_analyst),
):
    """
    Generates a PDF intelligence report using Catalyst SmartBrowz.
    Optionally emails it via Catalyst Mail to the given recipients.
    """
    report_url = _build_report_url(request, current_user)
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"reports/vv_{request.report_type}_{timestamp}.pdf"

    background_tasks.add_task(
        _generate_and_store_report, report_url, filename, request.email_recipients
    )

    return {
        "message": "Report generation started",
        "report_type": request.report_type,
        "status": "processing",
        "estimated_seconds": 30,
    }


async def _generate_and_store_report(
    url: str, filename: str, recipients: List[str]
):
    """Background task: generate PDF via SmartBrowz, upload to Stratus, email."""
    import tempfile, os

    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        tmp_path = tmp.name

    try:
        await CatalystSmartBrowz.generate_pdf(url, tmp_path)
        await CatalystStratus.upload_file("reports", tmp_path, filename)

        if recipients:
            signed_url = await CatalystStratus.get_signed_url("reports", filename, expiry_seconds=86400)
            await CatalystMail.send(
                to=recipients,
                subject="VigilanteVanguard — Intelligence Report Ready",
                body=f"""
                <h2>Karnataka State Police Intelligence Report</h2>
                <p>Your report has been generated and is ready for download.</p>
                <p><a href="{signed_url}">Download Report (valid 24 hours)</a></p>
                <p><small>Generated by VigilanteVanguard | Catalyst SmartBrowz + Mail</small></p>
                """,
            )
    finally:
        os.unlink(tmp_path)


def _build_report_url(request: ReportRequest, user: AuthUser) -> str:
    """Constructs the frontend report page URL for SmartBrowz to capture."""
    base = "https://vigilante-vanguard.catalystslate.com"
    if request.report_type == "daily_brief":
        return f"{base}/reports/daily?date={date.today()}"
    elif request.report_type == "case_summary" and request.case_id:
        return f"{base}/reports/case/{request.case_id}"
    elif request.report_type == "district_report" and request.district_id:
        return f"{base}/reports/district/{request.district_id}"
    return f"{base}/reports/general"


@router.get("/daily-brief", summary="Get today's auto-generated daily brief")
async def get_daily_brief(
    current_user: AuthUser = Depends(require_analyst),
):
    """Returns today's scheduled daily intelligence briefing (generated by Catalyst Cron)."""
    today = date.today()
    sql = f"""
        SELECT cr.CrimeGroupName, SUM(1) as count, AVG(cm.Latitude) as avg_lat, AVG(cm.Longitude) as avg_lon
        FROM CaseMaster cm
        JOIN CrimeHead cr ON cm.CrimeMajorHeadID = cr.CrimeHeadID
        WHERE DATE(cm.CrimeRegisteredDate) = '{today}'
        GROUP BY cr.CrimeGroupName ORDER BY count DESC
    """
    rows = await CatalystDataStore.query(sql)
    return {
        "date": today.isoformat(),
        "generated_by": "Catalyst Cron + QuickML",
        "today_summary": rows,
    }
