"""
rpi_auto_fir.py — Auto-draft BNS 2023 FIR from AI incident detection
=====================================================================
When confidence >= 0.85, auto-fills a full BNS 2023-compliant FIR draft
and POSTs it to the VigilanteVanguard backend for officer countersignature.

BNS sections auto-mapped from incident type.
brief_facts paragraph generated by Gemini 2.0 Flash (or template fallback).

Install  : pip install requests

Usage    :
  from rpi_auto_fir import AutoFIR
  fir = AutoFIR()
  result = fir.create_draft(
      incident_id="INC-0001",
      incident_type="Road Accident",
      confidence=0.93,
      gps={"lat": 12.9716, "lng": 77.5946},
      vehicle_plates=["KA03MJ1234", "KA19AB5678"],
      victim_count=2,
      triage_code="T1",
      camera_name="CAM-BLR-001",
      evidence_hash="abc123…",
  )
  # result → {"crime_no": "C00050004202600001", "case_id": 1, "status": "DRAFT"}
"""

from __future__ import annotations

import json
import logging
import os
import time
from dataclasses import dataclass
from typing import List, Optional

import requests

log = logging.getLogger("vv.autofir")

VV_API_BASE     = os.environ.get("VV_API_BASE", "http://localhost:8000")
VV_TOKEN        = os.environ.get("VV_AUTO_FIR_TOKEN", "")   # admin token
GEMINI_API_KEY  = os.environ.get("GEMINI_API_KEY", "")
MIN_CONFIDENCE  = float(os.environ.get("AUTO_FIR_MIN_CONFIDENCE", "0.85"))

# BNS 2023 section mapping per incident type
_BNS_SECTIONS: dict[str, list] = {
    "Road Accident":       [{"act": "Motor Vehicles Act 1988", "section": "134", "description": "Duty of driver in case of accident"},
                            {"act": "BNS 2023",               "section": "281", "description": "Rash driving or riding on a public way"}],
    "Vehicle Collision":   [{"act": "Motor Vehicles Act 1988", "section": "134", "description": "Duty of driver in case of accident"}],
    "Physical Fight":      [{"act": "BNS 2023", "section": "115", "description": "Voluntarily causing hurt"},
                            {"act": "BNS 2023", "section": "351", "description": "Assault"}],
    "Weapon Detected":     [{"act": "BNS 2023",  "section": "110", "description": "Attempt to commit culpable homicide"},
                            {"act": "Arms Act",  "section": "25",  "description": "Punishment for certain offences"}],
    "Fire / Smoke":        [{"act": "BNS 2023", "section": "238", "description": "Negligent act likely to spread fire"}],
    "Theft / Robbery":     [{"act": "BNS 2023", "section": "303", "description": "Theft"},
                            {"act": "BNS 2023", "section": "309", "description": "Robbery"}],
    "Person Unconscious":  [{"act": "BNS 2023", "section": "125A", "description": "Endangering life or personal safety of others"}],
    "Suspicious Activity": [{"act": "Karnataka Police Act", "section": "109", "description": "Suspicious person"}],
}

# Default police station and officer for auto-FIR (overridden by station registry lookup)
_DEFAULT_STATION_ID = int(os.environ.get("DEFAULT_STATION_ID", "1"))
_DEFAULT_OFFICER_ID = os.environ.get("DEFAULT_OFFICER_ID", "1")


@dataclass
class FIRDraftResult:
    success:    bool
    crime_no:   str
    case_id:    Optional[int]
    status:     str       # "DRAFT" | "FAILED"
    brief_facts: str
    bns_sections: list
    error:      Optional[str] = None


class AutoFIR:
    """Creates draft FIRs automatically from AI incident detections."""

    def __init__(self, api_base: str = VV_API_BASE, token: str = VV_TOKEN):
        self._api = api_base
        self._headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        }

    # ── Public API ────────────────────────────────────────────────────────────

    def should_auto_create(self, confidence: float, incident_type: str) -> bool:
        """Decide whether to auto-create FIR based on confidence + type."""
        high_priority = {"Road Accident", "Weapon Detected", "Fire / Smoke", "Vehicle Collision"}
        threshold = MIN_CONFIDENCE if incident_type in high_priority else 0.92
        return confidence >= threshold

    def create_draft(
        self,
        incident_id: str,
        incident_type: str,
        confidence: float,
        gps: dict,
        vehicle_plates: List[str] = None,
        victim_count: int = 0,
        triage_code: str = "T2",
        camera_name: str = "",
        evidence_hash: str = "",
        station_id: int = _DEFAULT_STATION_ID,
    ) -> FIRDraftResult:
        """
        Build and POST a draft FIR to the VV backend.
        Returns FIRDraftResult with crime_no on success.
        """
        if not self.should_auto_create(confidence, incident_type):
            return FIRDraftResult(
                success=False, crime_no="", case_id=None,
                status="SKIPPED", brief_facts="",
                bns_sections=[], error="Confidence below threshold"
            )

        sections = _BNS_SECTIONS.get(incident_type, [])
        brief_facts = self._generate_brief_facts(
            incident_id, incident_type, confidence, gps,
            vehicle_plates or [], victim_count, triage_code,
            camera_name, evidence_hash,
        )

        payload = {
            "police_station_id":   station_id,
            "case_category_id":    1,
            "crime_major_head_id": self._crime_head_id(incident_type),
            "incident_from_date":  time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "latitude":            gps.get("lat", 0.0),
            "longitude":           gps.get("lng", 0.0),
            "brief_facts":         brief_facts,
            "act_sections":        sections,
            "complainants":        [],   # officer countersigns — they fill complainant
            "victims":             self._build_victims(victim_count, triage_code),
            "accused":             [],
            "is_auto_draft":       True,
            "ai_incident_id":      incident_id,
            "ai_confidence":       confidence,
            "ai_evidence_hash":    evidence_hash,
            "vehicle_plates":      vehicle_plates or [],
        }

        try:
            r = requests.post(
                f"{self._api}/api/v1/fir/",
                json=payload,
                headers=self._headers,
                timeout=10,
            )
            if r.status_code in (200, 201):
                data = r.json()
                crime_no = data.get("crime_no", "")
                case_id  = data.get("case_master_id")
                log.info("Auto-FIR created: %s (case_id=%s)", crime_no, case_id)
                return FIRDraftResult(
                    success=True, crime_no=crime_no, case_id=case_id,
                    status="DRAFT", brief_facts=brief_facts, bns_sections=sections,
                )
            else:
                log.error("FIR API error %d: %s", r.status_code, r.text[:120])
                return FIRDraftResult(
                    success=False, crime_no="", case_id=None,
                    status="FAILED", brief_facts=brief_facts, bns_sections=sections,
                    error=f"HTTP {r.status_code}",
                )
        except Exception as e:
            log.error("Auto-FIR request failed: %s", e)
            return FIRDraftResult(
                success=False, crime_no="", case_id=None,
                status="FAILED", brief_facts=brief_facts, bns_sections=sections,
                error=str(e),
            )

    # ── Brief facts generation ────────────────────────────────────────────────

    def _generate_brief_facts(
        self, incident_id, incident_type, confidence, gps,
        plates, victim_count, triage_code, camera_name, evidence_hash,
    ) -> str:
        """Try Gemini; fall back to deterministic template."""
        if GEMINI_API_KEY:
            try:
                return self._gemini_brief_facts(
                    incident_type, confidence, gps, plates,
                    victim_count, triage_code, camera_name,
                )
            except Exception as e:
                log.warning("Gemini failed (%s) — using template", e)
        return self._template_brief_facts(
            incident_id, incident_type, confidence, gps,
            plates, victim_count, triage_code, camera_name, evidence_hash,
        )

    def _gemini_brief_facts(self, incident_type, confidence, gps,
                            plates, victim_count, triage_code, camera_name) -> str:
        prompt = (
            f"Write a concise, formal FIR brief_facts paragraph in English for a "
            f"'{incident_type}' incident detected by AI CCTV system VigilanteVanguard "
            f"with {confidence:.0%} confidence. "
            f"Location: {gps.get('lat'):.5f}N, {gps.get('lng'):.5f}E. "
            f"Camera: {camera_name}. "
            f"Vehicles involved: {', '.join(plates) or 'unknown'}. "
            f"Victims: {victim_count} (Triage: {triage_code}). "
            f"Use BNS 2023 terminology. Keep under 150 words. "
            f"State this is an AI-assisted preliminary FIR pending officer verification."
        )
        import requests as req
        r = req.post(
            f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={GEMINI_API_KEY}",
            json={"contents": [{"parts": [{"text": prompt}]}]},
            timeout=8,
        )
        r.raise_for_status()
        return r.json()["candidates"][0]["content"]["parts"][0]["text"].strip()

    @staticmethod
    def _template_brief_facts(incident_id, incident_type, confidence, gps,
                               plates, victim_count, triage_code,
                               camera_name, evidence_hash) -> str:
        ts = time.strftime("%d/%m/%Y at %H:%M:%S IST", time.localtime())
        plates_str = ", ".join(plates) if plates else "not identified"
        return (
            f"On {ts}, the VigilanteVanguard AI surveillance system detected a "
            f"'{incident_type}' at GPS coordinates {gps.get('lat'):.5f}N, "
            f"{gps.get('lng'):.5f}E via camera {camera_name} with AI confidence "
            f"{confidence:.0%}. {victim_count} victim(s) observed (triage: {triage_code}). "
            f"Vehicles involved: {plates_str}. "
            f"Incident reference: {incident_id}. "
            f"Evidence hash (SHA-256): {evidence_hash[:32]}… "
            f"This is an AI-assisted preliminary FIR draft pending verification and "
            f"countersignature by the duty officer as per BNSS 2023."
        )

    @staticmethod
    def _crime_head_id(incident_type: str) -> int:
        mapping = {
            "Road Accident": 12, "Vehicle Collision": 12,
            "Physical Fight": 3, "Weapon Detected": 1,
            "Fire / Smoke": 9,   "Theft / Robbery": 5,
            "Person Unconscious": 10, "Suspicious Activity": 15,
        }
        return mapping.get(incident_type, 15)

    @staticmethod
    def _build_victims(count: int, triage_code: str) -> list:
        return [
            {"victim_type": "Unknown", "triage_code": triage_code,
             "notes": f"Victim {i+1} — details pending officer arrival"}
            for i in range(min(count, 10))
        ]


# ── Module-level singleton ─────────────────────────────────────────────────────
_auto_fir: Optional[AutoFIR] = None


def get_auto_fir() -> AutoFIR:
    global _auto_fir
    if _auto_fir is None:
        _auto_fir = AutoFIR()
    return _auto_fir
